### ISSUE TITLE
Create Dialog Fails

### ISSUE THREAD

**Issue by dietzc** [knime-ip/knip-scripting#87]
```
Compiling 1 file in /tmp/java4523300393221565066
/tmp/java4523300393221565066/src/main/java/script/Script.java:10: error: cannot find symbol
public class Script<T extends RealType<T>> implements Command { 
                              ^
  symbol: class RealType
/tmp/java4523300393221565066/src/main/java/script/Script.java:13: error: cannot find symbol
	private Img<T> img;
	        ^
  symbol:   class Img
  location: class Script<T>
  where T is a type-variable:
    T declared in class Script
2 errors
java.lang.ClassNotFoundException: script.Script
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.scijava.plugins.scripting.java.JavaEngine.compile(JavaEngine.java:228)
	at org.scijava.plugins.scripting.java.JavaEngine.compile(JavaEngine.java:264)
	at org.knime.scijava.scripting.base.CompileHelper.compile(CompileHelper.java:86)
	at org.knime.scijava.scripting.nodes.interactive.ui.SciJavaScriptingNodeDialog.recompile(SciJavaScriptingNodeDialog.java:407)
	at org.knime.scijava.scripting.nodes.interactive.ui.SciJavaScriptingNodeDialog.createDialogPanel(SciJavaScriptingNodeDialog.java:276)
	at org.knime.scijava.scripting.nodes.interactive.ui.SciJavaScriptingNodeDialog.access$3(SciJavaScriptingNodeDialog.java:266)
	at org.knime.scijava.scripting.nodes.interactive.ui.SciJavaScriptingNodeDialog$ModeSwitchButtonListener.actionPerformed(SciJavaScriptingNodeDialog.java:540)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Script is: 

```
package script;

import org.scijava.plugin.Parameter;
import org.scijava.plugin.Plugin;
import org.scijava.ItemIO;
import org.scijava.command.Command;
import org.scijava.plugin.Attr;

@Plugin(type = Command.class)
public class Script<T extends RealType<T>> implements Command { 

	@Parameter(type = ItemIO.INPUT, attrs = {@Attr(name = "columnSelect", value = "true"), @Attr(name= "defaultColumn", value = "Img")})
	private Img<T> img;

	/*
	 * Parameters
	 * 
	 * Define inputs and/or outputs of your script.
	 * By annotating a member with
	 *  -> @Parameter(type = ItemIO.INPUT) you define an input
	 *	-> @Parameter(type = ItemIO.OUTPUT) you define an output
	 *	-> @Parameter(type = ItemIO.BOTH) you define a member to
	 *	   be both input and output.
	 */
	
	public void run() {

		/*
		 * Put code which evaluates the parameters here.
		 * 
		 * To output something to a table row, you merely need to
		 * set output parameters. They will be automatically result
		 * in column in the output table.
		 */
		
	}
}
```

**Comment by dietzc** [comment]
I know `RealType` is not imported, however, it doesn't show me any error about this?!

**Comment by dietzc** [comment]
resolved with dependency package. @gab1one can you double check?
